#!/usr/bin/env php
<?php
// application.php

/*
 * possibili comandi
 *
 *  ./pushsender list
 *  ./pushsender help send
 *
 */

require __DIR__.'/vendor/autoload.php';

use Tabasoft\SendPushCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new SendPushCommand());
$application->run();